export const LOAD_LOGGED_USER_SUCCESS = "LOAD_LOGGED_USER_SUCCESS";
export const SHOW_USER_ACTION_ERROR = "SHOW_USER_ACTION_ERROR";
export const HIDE_MESSAGE = "HIDE_MESSAGE";
export const SHOW_USER_ACTION_SUCCESS = "SHOW_USER_ACTION_SUCCESS";
export const INVALIDATE_USER = "INVALIDATE_USER";
